//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dpark.Localization {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dpark.Localization.TextResources", typeof(TextResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Directions.
        /// </summary>
        internal static string Get_Directions {
            get {
                return ResourceManager.GetString("Get_Directions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Application?.
        /// </summary>
        internal static string Leave_Application {
            get {
                return ResourceManager.GetString("Leave_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, Leave.
        /// </summary>
        internal static string Leave_Mapping_Yes {
            get {
                return ResourceManager.GetString("Leave_Mapping_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to leave the Dpark app and get directions?.
        /// </summary>
        internal static string Leave_MappingDirections {
            get {
                return ResourceManager.GetString("Leave_MappingDirections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action requires access to remote data, but you don&apos;t seem to currently have a network connnection. Check your connection and try again..
        /// </summary>
        internal static string NetworkConnection_Alert_Message {
            get {
                return ResourceManager.GetString("NetworkConnection_Alert_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Connected?.
        /// </summary>
        internal static string NetworkConnection_Alert_Title {
            get {
                return ResourceManager.GetString("NetworkConnection_Alert_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try Again.
        /// </summary>
        internal static string NetworkConnection_Alert_TryAgain {
            get {
                return ResourceManager.GetString("NetworkConnection_Alert_TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Refresh_Space {
            get {
                return ResourceManager.GetString("Refresh_Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We were unable to determine the location. Please try updating your address again with more common street, city and region names..
        /// </summary>
        internal static string SearchNotFound_Message {
            get {
                return ResourceManager.GetString("SearchNotFound_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found?.
        /// </summary>
        internal static string SearchNotFound_Title {
            get {
                return ResourceManager.GetString("SearchNotFound_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found no accessible spots within the ten miles radius. To make sure the address is search correctly, please try updating your address again with more common street, city and region names..
        /// </summary>
        internal static string SearchSpaceNearby_Message {
            get {
                return ResourceManager.GetString("SearchSpaceNearby_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spots Nearby?.
        /// </summary>
        internal static string SearchSpaceNearby_Title {
            get {
                return ResourceManager.GetString("SearchSpaceNearby_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try Again?.
        /// </summary>
        internal static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
    }
}
